### ISSUE TITLE
Extend to Linked Tables

### ISSUE THREAD

**Issue by app-generator** [app-generator/django-api-generator#2]
In the current version, the generator knows how to deal with isolated tables.
The goal of the new iteration is to support linked tables like this sample:

### Sample Models 

- Product Model
  - ID (numeric, autoincrement)
  - name (string)
  - price (numeric)
  - information (string)

- Sales Model
  - ID (numeric, autoincrement)
  - Product (1-1 relation with product)  # <-- THIS IS DIFFERENT 
  - quantity (numeric)
  - fees (numeric)
  - purchase_date (UNIX timestamp) 
  - refunded (boolean)
  - comments (string)

### Currently, this is the flow:

- Models need to exist & migrated on DB
- User edits the configuration and adds the models 
  - see the syntax on README 
- Run the generator via CLI
  - `python manage.py generate-api`
- Use the code in the APP 

 Ty!

**Comment by masoom80** [comment]
Hello @app-generator.
Could you give me a detailed sample of what exactly the post, put, and get should be like for the example above?

**Comment by app-generator** [comment]
Hello @masoom80 

The easy way is to install the library and generate the API for `Product Model` 
All the flow is documented on the README. 

Once this phase is done, and you're accommodated with the concept, try to generate the code for a `Sales` model that has a link to Products. 

In the current version, the API generator works for isolated tables. 
The evolution needs to handle the case when the tables are linked. 

Let me know if you have further Q. 
Ty!

**Comment by masoom80** [comment]
Hi again  @app-generator.
I worked it out and now am familiar with the current flow.
I don't know what the problem is.
Should the new one show the full products fields(currently it only shows their id.)?

**Comment by app-generator** [comment]
Hello @masoom80 

I'm testing the latest features & also created a test project where we will experiment all cases. 

Please wait.

**Comment by app-generator** [comment]
validated. closing.
